version: '3'
services:
  rpa-bpo-dashboard-nginx:
    container_name: ${PROJECT_NAME}-nginx
    image: '${PROJECT_NAME}-nginx:latest'
    restart: always
    environment:
      - TZ=Asia/Seoul
      - SERVICE_NAME=nginx
    env_file:
      - .env
    volumes:
      - ./.docker/ssl:/etc/nginx/ssl
    networks:
      - app
      - consul
    ports:
      - ${PROJECT_PORT}:${PROJECT_PORT}
      - 8093:8093
networks:
  app:
  consul:
    external:
      name: consul
