version: '3'

services:
  ${PROJECT_NAME}-nginx:
    container_name: ${PROJECT_NAME}-nginx
    image: ${PROJECT_NAME}-nginx:latest
    build: ./.docker/nginx/
    restart: always
    environment:
      - TZ=Asia/Seoul
      - 'APP_URL=${APP_URL}'
      - 'USE_COMMERCIAL_SSL=${USE_COMMERCIAL_SSL}'
      - 'SSL_NAME=${SSL_NAME}'
      - SERVICE_NAME=nginx
    networks:
      - app
      - consul
    ports:
      - '80:80'
      - '443:443'
      - '8093:8093'

networks:
  app:
  consul:
    external:
      name: consul
