version: '3'
services:
  ${PROJECT_NAME}-blue:
    container_name: ${PROJECT_NAME}-blue
    stdin_open: true
    tty: true
    image: ${PROJECT_NAME}:blue
    restart: always
    networks:
      - app
      - consul
    extra_hosts:
      - "${HOST_IP}:host-gateway"
    environment:
      - SERVICE_NAME=blue
      - XDEBUG_CONFIG=idekey=IDE_DEBUG
      - PHP_IDE_CONFIG=serverName=laravel-crud-boilerplate
    env_file:
      - .env
    volumes:
      - ${HOST_ROOT_LOCATION}:${PROJECT_LOCATION}:rw
      - ./.docker/ssl:${CONTAINER_SSL_VOLUME_PATH:-/.devnull}
  ${PROJECT_NAME}-green:
    container_name: ${PROJECT_NAME}-green
    stdin_open: true
    tty: true
    image: ${PROJECT_NAME}:green
    restart: always
    networks:
      - app
      - consul
    extra_hosts:
      - "${HOST_IP}:host-gateway"
    environment:
      - SERVICE_NAME=green
      - XDEBUG_CONFIG=idekey=IDE_DEBUG
      - PHP_IDE_CONFIG=serverName=laravel-crud-boilerplate
    env_file:
      - .env
    volumes:
      - ${HOST_ROOT_LOCATION}:${PROJECT_LOCATION}:rw
      - ./.docker/ssl:${CONTAINER_SSL_VOLUME_PATH:-/.devnull}
networks:
  app:
  consul:
    external:
      name: consul
