version: '3.7'
services:
  spring-sample-h-auth:
    stdin_open: true
    tty: true
    image: spring-sample-h-auth:blue
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SERVICE_NAME=blue
    env_file:
      - .env
    volumes: []
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
