version: '3'
services:
  node-express-boilerplate-blue:
    container_name: ${PROJECT_NAME}-blue
    stdin_open: true
    tty: true
    image: ${PROJECT_NAME}:blue
    restart: always
    networks:
      - app
      - consul
    extra_hosts:
      - "${HOST_IP}:host-gateway"
    environment:
      - SERVICE_NAME=blue
      - MONGODB_URL=mongodb://host.docker.internal:27017/node-boilerplate
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ${HOST_ROOT_LOCATION}:${PROJECT_LOCATION}:rw
      - ./.docker/ssl:${CONTAINER_SSL_VOLUME_PATH:-/.devnull}
  node-express-boilerplate-green:
    container_name: ${PROJECT_NAME}-green
    stdin_open: true
    tty: true
    image: ${PROJECT_NAME}:green
    restart: always
    networks:
      - app
      - consul
    extra_hosts:
      - "${HOST_IP}:host-gateway"
    environment:
      - SERVICE_NAME=green
      - MONGODB_URL=mongodb://host.docker.internal:27017/node-boilerplate
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ${HOST_ROOT_LOCATION}:${PROJECT_LOCATION}:rw
      - ./.docker/ssl:${CONTAINER_SSL_VOLUME_PATH:-/.devnull}
networks:
  app:
  consul:
    external:
      name: consul
