version: '3'
services:
  rpa-bpo-dashboard-blue:
    container_name: ${PROJECT_NAME}-blue
    stdin_open: true
    tty: true
    image: ${PROJECT_NAME}:blue
    restart: always
    networks:
      - app
      - consul
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=Asia/Seoul
      - SERVICE_NAME=blue
    env_file:
      - .env
    volumes:
      - ${HOST_ROOT_LOCATION}:${PROJECT_LOCATION}/${PROJECT_NAME}:rw
      - ./.docker/ssl:${CONTAINER_SSL_VOLUME_PATH:-/.devnull}
  rpa-bpo-dashboard-green:
    container_name: ${PROJECT_NAME}-green
    stdin_open: true
    tty: true
    image: ${PROJECT_NAME}:green
    restart: always
    networks:
      - app
      - consul
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=Asia/Seoul
      - SERVICE_NAME=green
    env_file:
      - .env
    volumes:
      - ${HOST_ROOT_LOCATION}:${PROJECT_LOCATION}/${PROJECT_NAME}:rw
      - ./.docker/ssl:${CONTAINER_SSL_VOLUME_PATH:-/.devnull}
networks:
  app:
  consul:
    external:
      name: consul
