version: '3'
services:
  ${PROJECT_NAME}-nginx:
    image: 'spring-sample-h-auth-nginx:latest'
    environment:
      - TZ=Asia/Seoul
      - SERVICE_NAME=nginx
    env_file:
      - .env
    volumes:
      - ./.docker/ssl:/etc/nginx/ssl
      - ./.docker/nginx/ctmpl:/ctmpl
    ports:
      - 18200:18200
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 0s
