version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.08
    steps:
      - run:
          name: Docker Login
          command: echo "$DOCKERHUB_PASS" | docker login -u $DOCKERHUB_USER --password-stdin
      - checkout
      - run:
          name: Execute run.sh
          command: sudo bash ./run.sh

workflows:
  version: 2
  main_workflow:
    jobs:
      - build